feat(cli) link revamp
alpenlabs/alpen pull request #487
Opened 2024-11-27 10:23 UTC by Zk2u

## Description

Revamps link building and pretty printing for the cli. 

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [x] Refactor
-   [ ] New or updated tests

## Checklist

-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

## Related Issues

STR-637
STR-657

2024-11-27 13:29 UTC, storopoli requested changes
We need docstrings.

Also, was surprised that you did not use `terrors::OneOf` here.

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +}
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +pub trait PrettyPrint {
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    pub fn with_explorer<'b>(self, explorer_domain: &'b str) -> Link<'a, 'b> {
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    pub fn with_maybe_explorer<'b>(self, explorer_domain: Option<&'b str>) -> MaybeLink<'a, 'b> {
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +}
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +}
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +}
docstrings

2024-11-27 13:29 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +pub struct Link<'a, 'b> {
struct docstrings

2024-11-27 13:44 UTC, Zk2u commented
OneOfs are heap allocated + while they're not limited to errors, the main advantage is to do layered handling of the possible types, narrowing and broadening. Outside of this super useful functionality, heap allocating it is pretty shit. Heap allocation is ok for errors as they aren't in hot paths. But for this, enums are much more appropriate and more efficient. Only use oneofs when you need to!

2024-11-27 13:48 UTC, storopoli commented
> heap allocating it is pretty shit.

Yes, forgot about that caveat 👍🏻.

2024-11-27 14:57 UTC, storopoli requested changes
Minor nits.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +/// A thing that exists or is represented onchain.
```suggestion
/// Represents anything that can be represented on-chain.
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +/// Currently, this is either a transaction or an address.
```suggestion
```
This is bad. If we add more enum variants we need to update the docstring, and highly likely this will not be done.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Transaction(Txid<'a>),
```suggestion
    /// On-chain Transaction ID.
    Transaction(Txid<'a>),
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +/// A thing that exists or is represented onchain.
Also, is this valid for Strata as well? Or just bitcoin?
Could be more clear of what `on-chain` means in the docstring.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Address(Address<'a>),
```suggestion
    /// On-chain Address.
    Address(Address<'a>),
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// Create a link to the object on the given explorer.
```suggestion
    /// Creates a link to the object on the given explorer.
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// Should be of the form `http{s}://{domain}`.
```suggestion
    /// Should be of the form `http{s}://{domain}`.
    ///
    /// # Examples
    ///
    /// PLEASE ADD AN EXAMPLE.
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// Create a link to the object on the given explorer, if it exists.
```suggestion
    /// Creates a link to the object on the given explorer, if it exists.
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// Should be of the form `http{s}://{domain}`.
Also add an example as mentioned above.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// This is primarily a helper for displaying an OnChainObject in a user-facing context.
```suggestion
    /// This is primarily a helper for displaying an [`OnChainObject`] in a user-facing context.
```
doc-link

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Object(OnchainObject<'a>),
docstrings in the variants.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Strata(&'a TxHash),
docstring in the variants.

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +/// A wrapper around a bitcoin transaction id or a strata transaction id.
```suggestion
/// A wrapper around a bitcoin transaction ID or a Strata transaction ID.
```

2024-11-27 14:57 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +/// This is primarily a helper for displaying an OnChainObject in a user-facing
```suggestion
/// This is primarily a helper for displaying an [`OnChainObject`] in a user-facing
```

2024-11-27 15:58 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Object(OnchainObject<'a>),
Yes, it is but I think we should lean towards more verbose documentation and add docstrings to anything that is `pub` (and some intricate not `pub`) stuff.

2024-11-27 15:58 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    Strata(&'a TxHash),
Yes, it is but I think we should lean towards more verbose documentation and add docstrings to anything that is `pub` (and some intricate not `pub`) stuff.

2024-11-28 17:22 UTC, delbonis approved these changes

2024-11-28 18:07 UTC, storopoli commented on bin/strata-cli/src/link.rs
> +    /// Should be of the form `http{s}://{domain}`.
Glad that you added an example.
Because I thought reading from the docstring that you don't need the `.tld` part.
Only `https://mempool`.

2024-11-28 18:07 UTC, storopoli approved these changes
ACK c4f2d7baa9b979b8a49487f25dc5eedcd802968c

2024-11-28 18:54 UTC, merged